Create Typescript file
pofigizm/redux-dynamic-middlewares pull request #11
Opened 2021-09-10 07:57 UTC by pablogdcr

2021-12-15 17:38 UTC, IlliaAgility commented
All is fine! You can merge it

2022-03-10 14:16 UTC, silenzium commented
can someone with access merge this please? :)

2022-03-10 14:30 UTC, silenzium requested changes

2022-03-10 14:30 UTC, silenzium commented on src/index.d.ts
> +  enhancer: Middlware,
this should be `Middleware` instead of `Middlware`.

2022-04-06 06:49 UTC, merged

2022-04-06 06:50 UTC, pofigizm commented
Good job
Thank you

2022-04-06 06:50 UTC, pofigizm commented
Sorry for waiting